oilsite/__init__.py
from flask import Flask, render_template
# db import
from datetime import datetime
from flask.ext.mongoengine import MongoEngine

# admin import
from flask_admin.contrib.mongoengine import ModelView
import flask_admin as admin
from flask_admin.form import rules

# navigation import
from flask.ext.navigation import Navigation


app = Flask(__name__)

app.config["MONGODB_SETTINGS"] = {'DB': "mng_oilbase"}
app.config["SECRET_KEY"] = "password"

# db part 

db = MongoEngine()
db.init_app(app)

class Descriptions(db.Document):
	__tablename__ = "Описания"
	title = db.StringField(max_length=255, required=True)
	description = db.StringField(required=True)
	image = db.ListField(db.StringField(max_length=100))

class Slogans(db.Document):
	__tablename__ = "Слоганы"
	title = db.StringField(max_length=255, required=True)
	description = db.StringField(required=True)
	page = db.StringField(max_length=20, required=True)

class Dilers(db.Document):
	__tablename__ = "Дилеры"
	city = db.StringField(max_length=100, required=True)
	address = db.StringField(max_length=400, required=True)
	phone = db.StringField(max_length=30, required=True)
	coords = db.StringField(max_length=30, required=True)
	email = db.StringField(required=True)

class Personal(db.EmbeddedDocument):
	__tablename__ = "Персонал"
	name = db.StringField(max_length=250, required=True)
	post = db.StringField(max_length=250, required=True)
	phone = db.StringField(max_length=30, required=True)
	email = db.StringField(required=True)

class Departaments(db.Document):
	__tablename__ = "Отделы"
	title = db.StringField(max_length=100, required=True)
	worktime = db.ListField(db.StringField(max_length=100))
	personal = db.ListField(db.EmbeddedDocumentField('Personal'))

	def __unicode__(self):
		return self.title

	meta = {
		'allow_inheritance':True
	}

class Contacts(db.Document):
	__tablename__ = "Контакты"
	name = db.StringField(max_length=450, required=True)
	address = db.StringField(max_length=250, required=True)
	coords = db.StringField(max_length=30, required=True)
	site = db.StringField(max_length=20, required=True)
	email = db.StringField(required=True)

class CallBack(db.Document):
	__tablename__ = "Обратная связь"
	name = db.StringField(max_length=200, required=True)
	email = db.StringField(max_length=20, required=True)
	phone = db.StringField(max_length=20, required=True)
	message = db.StringField(required=True)

class Products(db.EmbeddedDocument):
	__tablename__ = "Товары"
	title = db.StringField(max_length=100, required=True)
	image = db.StringField(max_length=100, required=True)
	description = db.StringField(max_length=250, required=True)
	content = db.StringField(max_length=100, required=True)
	gost = db.StringField(max_length=250, required=True)
	docs = db.StringField(max_length=250, required=True)
	cost = db.IntField(required=True)
	send_type = db.StringField(max_length=250, required=True)


class Categories(db.Document):
	__tablename__ = "Категории"
	title = db.StringField(max_length=100, required=True)
	description = db.StringField(required=True)
	products = db.ListField(db.EmbeddedDocumentField('Products'))


# admin part

class DescriptionsView(ModelView):
	column_filters = ['title']
	column_searchable_list = ('title', 'description', )

class SlogansView(ModelView):
	column_filters = ['title']
	column_searchable_list = ('title', 'description', 'page',)

class ContactsView(ModelView):
	column_filters = ['name']
	column_searchable_list = ('name', 'address', 'coords', 'site', 'email',)

class DilersView(ModelView):
    column_filters = ['city']
    column_searchable_list = ('city', 'address', 'phone', 'coords', 'email',)

class CallBackView(ModelView):
	column_filters = ['name']
	column_searchable_list = ('name', 'email', 'phone', 'message', )

class CategoriesView(ModelView):
	column_filters = ['title']
	column_searchable_list = ('title', 'description',)
	form_subdocuments = {
        'products': {
            'form_rules': ('title', rules.HTML('<hr>'), 'code')
        }
    }

class DepartamentsView(ModelView):
	column_filters = ['title']
	column_searchable_list = ('title', )
	form_subdocuments = {
        'personal': {
            'form_rules': ('name', rules.HTML('<hr>'), 'code')
        }
    }

admin = admin.Admin(app, 'Нефтебаза: администрирование')
admin.add_view(DilersView(Dilers))
admin.add_view(CallBackView(CallBack))
admin.add_view(CategoriesView(Categories))
admin.add_view(DepartamentsView(Departaments))
admin.add_view(ContactsView(Contacts))
admin.add_view(DescriptionsView(Descriptions))
admin.add_view(SlogansView(Slogans))

# register blueprints for views

def register_blueprints(app):
	from oilsite.views import oilsite
	app.register_blueprint(oilsite)

register_blueprints(app)

# navigation part
nav = Navigation()
nav.init_app(app)

products_array = []
categs = Categories.objects.all().order_by('title')
for el in categs:
	products_array.append(nav.Item(el.title, 'products', {'product': el.title}))

nav.Bar('top', [
		nav.Item('Продукция','products', {'product':'Бензин'}, items = products_array),
		nav.Item('Доставка', 'delivery'),
		nav.Item('Дилеры', 'dilers'),
		nav.Item('Контакты', 'contacts')
	])


@app.route('/contacts')
def contacts():
	return render_template('oilsite/contacts.html')

@app.route('/dilers')
def dilers():
	return render_template('oilsite/dilers.html')

@app.route('/delivery')
def delivery():
	return render_template('oilsite/delivery.html')

@app.route('/products/<product>/')
def products():
	return render_template('oilsite/products.html', product=product)

# end


if __name__ == '__main__':
	app.run()

oilsite/views.py
from flask.ext.mongoengine.wtf import model_form
from flask import Blueprint, request, redirect, render_template, url_for
from flask.views import MethodView
from oilsite import *
from wtforms import *

oilsite = Blueprint('oilsite', __name__, template_folder='templates')

class MainPage(MethodView):

	def get_context(self):
		desc = Descriptions.objects(image__size=1)
		carousel = Slogans.objects(page=u'Главная')

		context = {
			"desc":desc,
			"carousel":carousel
		}

		return context

	def get(self):
		context = self.get_context()
		return render_template('oilsite/main.html', **context)


class DeliveryPage(MethodView):

	def get_context(self):
		desc = Descriptions.objects(image__size=3)
		carousel = Slogans.objects(page=u'Доставка')

		context = {
			"desc":desc,
			"carousel":carousel
		}
		
		return context

	def get(self):
		context = self.get_context()
		return render_template('oilsite/delivery.html', **context)


class DilersPage(MethodView):

	def get(self):
		dilers = Dilers.objects.all()
		return render_template('oilsite/dilers.html', dilers=dilers)

class ContactsPage(MethodView):

	form = model_form(CallBack, field_args = {
		'name' : {'description':"Ваше имя"},
		'email' : {'description':"Ваш почтовый адрес"},
		'phone' : {'description':"Ваш телефон"},
		'message' : {'description':"Ваше сообщение"},
		})

	def get_context(self):
		contacts = Contacts.objects.all()
		departs = Departaments.objects.all()
		departaments = Departaments.objects(title = u"Администрация").get()
		main_persons = departaments['personal']
		departaments = Departaments.objects(title = u"Центр поставок").get()
		send_persons = departaments['personal']
		form = self.form(request.form)

		context = {
			"form":form,
			"contacts":contacts,
			"departs":departs,
			"main_persons":main_persons,
			"send_persons":send_persons
		}

		return context

	def get(self):
		context = self.get_context()
		return render_template('oilsite/contacts.html', **context)

	def post(self):
		context = self.get_context()
		form = context.get('form')

		if form.validate():
			callback = CallBack()
			form.populate_obj(callback)
			callback.save()

			return redirect(url_for('oilsite.contacts'))

		return render_template('oilsite/contacts.html', **context)


class ProductsPage(MethodView):

	def get_context(self, product):
		product = product.strip()
		categories = Categories.objects.all().order_by('title')

		prev_el = Categories.objects(title__lt=product).order_by('title')
		if prev_el.first() is None:
			prev_el = Categories.objects().all().order_by('title')[len(Categories.objects) - 1].title
		else:
			prev_el = prev_el[len(prev_el) - 1].title

		next_el = Categories.objects(title__gt=product).order_by('title').first()
		if next_el is None:
			next_el = Categories.objects().order_by('title').first().title
		else:
			next_el = next_el.title

		item = {"current": product, "next":next_el, "prev":prev_el}
		product = Categories.objects(title=product).get()['products']
		context = {
			"categories":categories,
			"product":product,
			"item":item
		}

		return context

	def get(self, product):
		context = self.get_context(product)
		return render_template('oilsite/products.html', **context)


oilsite.add_url_rule('/', view_func=MainPage.as_view('main'))
oilsite.add_url_rule('/dilers', view_func=DilersPage.as_view('dilers'))
oilsite.add_url_rule('/delivery', view_func=DeliveryPage.as_view('delivery'))
oilsite.add_url_rule('/contacts', view_func=ContactsPage.as_view('contacts'))
oilsite.add_url_rule('/products/<product>/', view_func=ProductsPage.as_view('products'))

oilsite/templates/oilsite/contacts.html
{% extends 'base.html'%}
{% import '_forms.html' as forms %}

{% block content %}

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <div id="map" class="map"></div>
            <div class="container">
                <div class="carousel-caption">
                    <h2 itemprop="name"><b>&laquo;Связь с нами&raquo;</b></h2>
                </div>
            </div>
        </div>
    </div>
</div>

<b>
<div class="container marketing">
	<div class="row featurette">
		{% for el in contacts %}
        <h2 class="text-center">{{ el.name }}</h2>
        <div class="center-block">
            <div class="col-lg-6">
                <div class="panel-body">
                    <blockquote class="pull-right">
                        <div class="form-group js-map" data-coords="{{ el.coords }}" data-address="{{ el.address }}" data-zoom="9">
                            <div>{{ el.address }}</div>
                        </div>
                    </blockquote>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="panel-body">
                    <blockquote>
                        <div class="form-group">
                            <div>Адрес электронной почты: {{ el.email }}</div>
                            <div>Наш сайт: {{ el.site }}</div>
                        </div>
                    </blockquote>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <hr class="half-rule">

    <div class="row featurette">
    	<h2 class="text-center">График работы</h2>
        <div class="center-block">
        	{% for el in departs %}
            <div class="col-lg-6">
                <div class="panel-body">
                {% if loop.index is divisibleby(2) %}
                    <blockquote class="pull-left">
                {% else %}
    				<blockquote class="pull-right">
    			{% endif %}
                            <h4 class="lead"><b>{{ el.title }}</b></h4>
                            {% for time in el.worktime %}
                                <div class="text-center">{{ time }}</div>
                            {% endfor %}
                    </blockquote>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>     

	<hr class="half-rule">

        
    <div class="row featurette">
        <h2 class="text-center">Центр поставок</h2>
            <div class="center-block">
                <div class="col-lg-6">
                    <div class="panel-body">
                        <blockquote class="pull-right">
                            <dl class="dl-horizontal">
                                {% for el in send_persons %}
                                    {% if loop.index is divisibleby(2) %}
                                        <dt>{{ el.post }}</dt>
                                        <dd>{{ el.name }}</dd>
                                        <dd>Тел./факс: {{ el.phone }}</dd>
                                        <dd>E-mail: {{ el.email }}</dd>
                                    {% endif %}
                                {% endfor %}
                            </dl>
                        </blockquote>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="panel-body">
                        <blockquote>
                            <dl class="dl-horizontal">
                                {% for el in send_persons %}
                                    {% if not loop.index is divisibleby(2) %}
                                        <dt>{{ el.post }}</dt>
                                        <dd>{{ el.name }}</dd>
                                        <dd>Тел./факс: {{ el.phone }}</dd>
                                        <dd>E-mail: {{ el.email }}</dd>
                                    {% endif %}
                                {% endfor %}
                            </dl>
                        </blockquote>
                    </div>
                </div>
            </div>
    </div>

    <hr class="half-rule">

    <div class="row featurette">
        <h2 class="text-center">Администрация</h2>
            <div class="center-block">
                <div class="col-lg-6">
                    <div class="panel-body">
                        <blockquote class="pull-right">
                            <dl class="dl-horizontal">
                                {% for el in main_persons %}
                                    {% if loop.index is divisibleby(2) %}
                                        <dt>{{ el.post }}</dt>
                                        <dd>{{ el.name }}</dd>
                                        <dd>Тел./факс: {{ el.phone }}</dd>
                                        <dd>E-mail: {{ el.email }}</dd>
                                    {% endif %}
                                {% endfor %}
                            </dl>
                        </blockquote>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="panel-body">
                        <blockquote>
                            <dl class="dl-horizontal">
                                {% for el in main_persons %}
                                    {% if not loop.index is divisibleby(2) %}
                                        <dt>{{ el.post }}</dt>
                                        <dd>{{ el.name }}</dd>
                                        <dd>Тел./факс: {{ el.phone }}</dd>
                                        <dd>E-mail: {{ el.email }}</dd>
                                    {% endif %}
                                {% endfor %}
                            </dl>
                        </blockquote>
                    </div>
                </div>
            </div>
    </div>

    <hr class="half-rule">
    <div class="row featurette">
        <div class="modal-body row">
            <form class="form-signin" method="POST" id="submit-form">
                <h2 class="text-center">Обратная связь</h2>
                    {{ forms.render(form) }}
                        <div class="form-group">
                                    <div class="input-group col-md-12">
                                        <button class="btn btn-inverse btn-lg btn-block" type="submit">Отправить</button>
                                    </div>
                                </div>
                            </div>
            </form>
        </div>
    </div>

</b>
{% endblock content %}

oilsite/templates/oilsite/delivery.html
{% extends 'base.html'%}

{% block content %}

{% for el in carousel %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
            <div class="container">
                <div class="carousel-caption">
                    <h1>&laquo;{{ el.title }}&raquo;</h1>
                    <p>{{ el.description }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% for el in desc %}
<div class="container marketing">
    <div class="row featurette">
        <h3 class="text-left">{{ el.title }}</h3>
            <div class="center-block">
                <div class="panel-body">
    				{% for img in el.image %}
                    <div class="col-lg-4">
                        <img src="{{ img }}" class="img-rounded" alt="Cinque Terre" width="304" height="236"> 
                    </div>
                    {% endfor %}
                </div>
                <div class="text-left">{% autoescape off %}{{ el.description }}{% endautoescape %}</div>
            </div>
    </div>
    <hr class="featurette-divider">
{% endfor %}
{% endblock content %}

oilsite/templates/oilsite/dilers.html
{% extends 'base.html'%}

{% block content %}

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
        <div class="item active">
           <div id="map" class="map"></div>
            <div class="container">
                <div class="carousel-caption">
                    <h2 itemprop="name"><b>&laquo;Дилеры&raquo;</b></h2>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container marketing_dilers">   
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="row">
		{% for el in dilers %}
			<div class="col-xs-5 col-lg-4">
                <h3 class="text-left">{{ el.city }}</h3>
                <hr class="half-rule">
                <a href="#" data-coords="{{ el.coords }}" data-zoom="6" data-address="{{ el.address }}" class="js-map ">
                    <div class="text-left">{{ el.address }}</div>
                </a>
                {% if el.phone  %}
                	<div class="text-left">Тел./факс: {{ el.phone }}</div>
                {% endif%}
                {% if el.phone  %}
                	<div class="text-left">E-mail: {{ el.email }}</div>
                {% endif%}
                <hr class="half-rule">
         	</div>
		{% endfor %}
		</div>
	</div>

{% endblock content %}

oilsite/templates/oilsite/main.html
{% extends "base.html" %}

{% block content %}

<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
  	{% for el in carousel %}
  		{% if loop.index == 1 %}
    		<li data-target="#myCarousel" data-slide-to="{{ el.id }}" class="active"></li>
    	{% else %}
    		<li data-target="#myCarousel" data-slide-to="{{ el.id }}"></li>
    	{% endif %}
    {% endfor %}
  </ol>

  <div class="carousel-inner" role="listbox">
    {% for el in carousel %}
    {% if loop.index == 1 %}
    	<div class="item active">
    {% else %}
    	<div class="item">
    {% endif %}
      <img class="{{ el.id }}" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="{{ el.id }}">
      <div class="container">
        <div class="carousel-caption">
          <h1>&laquo;{{ el.title }}&raquo;</h1>
          <p>{{ el.description }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>



<div class="container marketing">
	{% for el in desc %}
	<div class="row featurette">
		{% if loop.index is divisibleby(2) %}
			<div class="col-md-7 col-md-push-5">
		{% else %}
    		<div class="col-md-7">
    	{% endif %}
      		<h2 class="featurette-heading">{{ el.title }}</h2>
      		<p class="lead">{% autoescape off %}{{ el.description }}{% endautoescape %}</p>
    	</div>
    	{% if loop.index is divisibleby(2) %}
			<div class="col-md-5 col-md-pull-7">
		{% else %}
    		<div class="col-md-5">
    	{% endif %}
    		{% for img in el.image %}
      		<img class="center-block" src="{{ img }}" alt="Generic placeholder image" width="450" height="450">
    		{% endfor %}
    	</div>
  	</div>
  	<hr class="featurette-divider">
  	{% endfor %}
{% endblock %}

oilsite/templates/oilsite/menu.html
<div class="navbar-wrapper">
  <div class="container">

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a  class="active navbar-brand" href="{{ url_for('oilsite.main') }}">Главная</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% url_for('oilsite.products') as url %}
            {% if url in path %}<li class="dropdown active">{% else %}<li class="dropdown">{% endif %}
              <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Продукция<span class="caret"></span></a>
              <ul class="dropdown-menu">
              {% for el in categories %}
                <li><a href="{{ url_for('oilsite.products', product=el.title) }}">{{ el.title }}</a></li>
              {% endfor %}
              </ul>
            </li>
            {% url_for('oilsite.dilers') as url %}
            {% if path == url %}<li class="active">{% else %} <li> {% endif %}<a href="{{ url_for('oilsite.dilers') }}">Дилеры</a></li>
            {% url_for('oilsite.delivery') as url %}
            {% if path == url %}<li class="active">{% else %} <li> {% endif %}<a href="{{ url_for('oilsite.delivery') }}">Доставка</a></li>
            {% url_for('oilsite.contacts') as url %}
            {% if path == url %}<li class="active">{% else %} <li> {% endif %}<a href="{{ url_for('oilsite.contacts') }}">Контакты</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</div>

oilsite/templates/oilsite/products.html
{% extends 'base.html'%}

{% block content %}
<div class="carousel slide">
  <ol class="carousel-indicators">
  	{% for el in categories %}
  		<a role="button" data-slide="prev" type="submit" method="Post" href="{{ url_for('oilsite.products', product=el.title) }}">
  		{% if el.title == item.current %}
    		<li data-slide-to="{{ el.title }}" class="active"></li>
    	{% else %}
    		<li data-slide-to="{{ el.title }}"></li>
    	{% endif %}
    	</a>
    {% endfor %}
  </ol>
  <div class="carousel-inner" role="listbox">
    {% for el in categories %}
    {% if el.title == item.current %}
    	<div class="item active">
    {% else %}
    	<div class="item">
    {% endif %}
      <img src="data:/image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==">
      <div class="container">
        <div class="carousel-caption">
          <h1>&laquo;{{ el.title }}&raquo;</h1>
          <p>{{ el.description }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <a class="left carousel-control" role="button" data-slide="prev" href="{{ url_for('oilsite.products', product=item.prev) }}">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" role="button" data-slide="next" href="{{ url_for('oilsite.products', product=item.next) }}">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</form>

<div class="container marketing">
    <div class="row row-offcanvas row-offcanvas-right">
        <div class="row">
            <div class="panel-body">
                {% for el in product %}
                	<div class="col-lg-6">
                        <h3 class="text-center">{{ el.title }}</h3>
                            <hr class="half-rule">
                                <img src="{{ el.image }}" class="center-block" width="200" height="200"> 
                            <hr class="half-rule">
                        <dl class="dl-horizontal">
                            <dt>Описание</dt>
                            <dd>{{ el.description }}</dd>

                            <dt>Тип доставки</dt>
                            <dd>{{ el.send_type }}</dd>
                            
                            <dt>Емкость</dt>
                            <dd>{{ el.content }}</dd>
                            
                            <dt>ГОСТ</dt>
                            <dd>{{ el.gost }}</dd>
                            
                            <dt>Паспорт качества</dt>
                            <dd>{{ el.docs }}</dd>
                        
                            <dt>Цена за единицу</dt>
                            <dd>{{ el.cost }} рублей</dd>
                        </dl>
                        <hr class="half-rule">
                	</div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}